### ISSUE TITLE
FIX: Update the logic for removing - more from youtube -  changes in youtube made in recent 

### ISSUE THREAD

**Issue by proffapt** [proffapt/own-youtube#1]
- [x] Ham-burger menu
- [x] Not that hard, just implement `more from youtube` removal and the footer of sidebar. It was working before but since youtube updated their website, this functionality broke.

Basically this..
<img width="225" alt="image" src="https://user-images.githubusercontent.com/86282911/179920228-1212f6d0-ebbe-4c76-9ab3-2cec822e109b.png">

**Comment by nidz27** [comment]
I have added the new elements in 'more from youtube', do you want me to remove the films, gaming,live,etc these options from 'more from youtube', they are actually available under explore and not 'more from youtube'. Also what is to be done about the settings,report history,etc.
![Screenshot from 2022-12-07 16-16-12](https://user-images.githubusercontent.com/95571961/206158918-aff6531d-80a1-4f03-a9bc-938fb00f05c5.png)

**Comment by proffapt** [comment]
> I have added the new elements in 'more from youtube'

Share one ss removing YT music. Along with the extension showing that feature enabled.

> do you want me to remove the films, gaming,live,etc these options from 'more from youtube', they are actually available under explore and not 'more from youtube'

Create a new section named "Explore" and shift them there.

> Also what is to be done about the settings,report history,etc.

Those are handled under the option `Footer Pane`. If you can separate them out as you did in more from youtube. That will be highly appreciated.

Good going. And also don't forget to see other features whether they are broken or not see #7

**Comment by proffapt** [comment]
And btw have you enrolled in KWoC?

**Comment by nidz27** [comment]
Yeah working on that tv issue...but that doesn't seem to be working yet

**Comment by nidz27** [comment]
It is working now
![Screenshot from 2022-12-08 12-57-26](https://user-images.githubusercontent.com/95571961/206385199-2a37663f-2542-4982-8fe0-5faa5d701498.png)

**Comment by proffapt** [comment]
> Should I go ahead and make a pr now or do you want me to change something before that?

If all the "more from youtube" things are fixed, then if you read this issue there's one more to do task - the ham burger menu when removed doesn't work like earlier.. if you click it.. it will open again but this isn't how it's supposed to work

After this is solved this issue can be closed when you make the PR, then you can work on other issues - I hope you are learning something along the process.
Best of luck!

**Comment by nidz27** [comment]
Can you please elaborate on the issue with ham burger menu...I am not getting it.
Thank you for guiding me through this and I am learning a lot actually. And it's an amazing project!

**Comment by proffapt** [comment]
> Can you please elaborate on the issue with ham burger menu...I am not getting it.

If you see in `Basic` -> `Sidebar` this feature was supposed to remove the side bar where home, subscription, more from youtube etc exist, it was supposed to collapse the sidebar and even on pressing the ham-burger menu on top left corner it won't come - but now if you click on it, you can still access it; this feature was working before the layout updates but not now; just look at the code and you will understand how it was doing it.. you just have to fix the changes made in youtube.

> Thank you for guiding me through this and I am learning a lot actually. And it's an amazing project!

Glad to read!

**Comment by nidz27** [comment]
> > Can you please elaborate on the issue with ham burger menu...I am not getting it.
> 
> If you see in `Basic` -> `Sidebar` this feature was supposed to remove the side bar where home, subscription, more from youtube etc exist, it was supposed to collapse the sidebar and even on pressing the ham-burger menu on top left corner it won't come - but now if you click on it, you can still access it; this feature was working before the layout updates but not now; just look at the code and you will understand how it was doing it.. you just have to fix the changes made in youtube.
> The sidebar is actually removing the right side bar when we play a video. And as for the left side bar, there is an option to purge it completely. If that option is selected even the hamburger menu icon disappears.

**Comment by nidz27** [comment]
The sidebar is actually removing the right side bar while playing a video. As for the left side bar there is an option to purge it completely, and this option removes the hamburger menu icon as well. So should the sidebar option remove both right and left?

**Comment by proffapt** [comment]
> The sidebar is actually removing the right side bar while playing a video. As for the left side bar there is an option to purge it completely, and this option removes the hamburger menu icon as well. So should the sidebar option remove both right and left?

Ahh yes my bad, When i tested I forgot about it, everything seems good to me then, will merge the pr when I reach home.

**Comment by proffapt** [comment]
You can make the pr now
