### ISSUE TITLE
Port the extension to Manifest version 3

### ISSUE THREAD

**Issue by proffapt** [proffapt/own-youtube#2]
Since manifest version 2 will be reaching its EOL soon (Refer: https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/). This extension needs to be updated to survive in future.
Would like for new contributors and beginners to carry out this not so hard task (not so easy either :) ).

**Comment by dudegladiator** [comment]
[own-youtube-main.zip](https://github.com/proffapt/own-youtube/files/10147415/own-youtube-main.zip)
I have updated to version 3 but now there are two more error.

**Comment by proffapt** [comment]
Mhmm, share you repository and branch in which you have worked upon

And for them to be counted in KWoC wait for the coding period to start, which is 6th December

**Comment by proffapt** [comment]
solved in #8
