### ISSUE TITLE
"In-video info cards" does not function

### ISSUE THREAD

**Issue by simrancs** [proffapt/own-youtube#27]
The "in-video info cards" under `Video Player > Remove Element Options` does **not** function; it does not remove the info cards whether the checkbox is checked or unchecked

**Screenshots:**
- Checkbox unchecked (no effect)
![image](https://user-images.githubusercontent.com/84126196/208247761-daaed764-81e6-4191-bffd-798f5fabb46a.png)
- Checkbox checked (no effect)
![image](https://user-images.githubusercontent.com/84126196/208247822-17f88ff7-4072-4e4b-aafa-ee245c706ad3.png)

**Comment by proffapt** [comment]
solved in #29
