### ISSUE TITLE
"Remove ads" works but functions opposite from the expected behavior

### ISSUE THREAD

**Issue by simrancs** [proffapt/own-youtube#28]
The "Remove ads" option under `Video Player > Dynamic Options` removes the ads before the video but in the opposite way as expected. 

**Expected behavior:**
- When the checkbox "Remove ads" is checked, it should remove ads but it does **not**.
- But when the checkbox "Remove ads" is unchecked, it should not remove ads but it removes.

Issue type: `easy`

**Comment by proffapt** [comment]
UMm.. that is sounding confusing to you since the roles of checkBoxes were flipped.
What we can do is change the name of Entry from "Remove ads" to just "Ads"

So, when the checkbox is ticked this means that the user wants to see ads, as in coherence with other elements and vice-versa.

**Comment by simrancs** [comment]
Agreed.

**Comment by proffapt** [comment]
Will not be a problem after #31

**Comment by simrancs** [comment]
Yea, perfect!
