### ISSUE TITLE
Improvement in the UI.

### ISSUE THREAD

**Issue by himanishu-2512** [proffapt/own-youtube#30]
**Is your feature request related to a problem? Please describe.**
There is improvement required in the UI(User Interface) of the extension.

**Describe the solution you'd like**
I come up with an idea to make a new UI for both light and dark theme. I'm attaching the screenshots of the new UI .

Old UI screenshot
Light theme:-
![image](https://user-images.githubusercontent.com/96021680/208316548-07447cb5-66ca-4ac9-92f0-802208e86964.png)
Dark theme:-
![image](https://user-images.githubusercontent.com/96021680/208316598-1f37d262-5fa7-4866-98be-b514880bbdc2.png)

New UI screenshot
Light theme:-
![image](https://user-images.githubusercontent.com/96021680/208317196-d3614cb0-1315-4158-9cbb-8bc369609979.png)
![image](https://user-images.githubusercontent.com/96021680/208317209-972800f2-f83c-431b-afba-8c616c37f85c.png)
![image](https://user-images.githubusercontent.com/96021680/208317230-0f94c748-d462-4acf-9b63-b796d91a587f.png)
Dark theme:-
![image](https://user-images.githubusercontent.com/96021680/208316667-9a45ce51-4357-4614-95db-13b9e6100761.png)
![image](https://user-images.githubusercontent.com/96021680/208316679-8b62884e-385d-424f-86ee-05bbb1d7418b.png)
![image](https://user-images.githubusercontent.com/96021680/208317244-76fe0334-5b4d-48e2-a7e6-61d47156f51e.png)

**Comment by proffapt** [comment]
Create a PR instead of an Issue and discuss further there.

**Comment by himanishu-2512** [comment]
ok
