### ISSUE TITLE
Automate Release workflow

### ISSUE THREAD

**Issue by proffapt** [proffapt/own-youtube#37]
The release workflow is to be automated:
- [ ] For github - ([done](https://github.com/proffapt/myREADME/blob/main/.github/workflows/release.yaml))
- [ ] For mozilla add-on store
- [ ] For chrome web store

Also, obviously first release on the the last two stores.
Automation is something not clear for those.. will have to research.

**Comment by harshau007** [comment]
Hey @proffapt, I would like to try to contribute to this issue.

**Comment by proffapt** [comment]
Great!, if you are contributing to KWoC then the coding period will start from 9th December. Till then I will assign you this.

**Comment by harshau007** [comment]
> Great!, if you are contributing to KWoC then the coding period will start from 9th December. Till then I will assign you this.

Thanks a lot
