### ISSUE TITLE
Add Shorts Blocking in Search Results Page...

### ISSUE THREAD

**Issue by e-xists** [proffapt/own-youtube#38]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by proffapt** [comment]
As far as I remember that does exist already?

**Comment by e-xists** [comment]
![image](https://github.com/proffapt/own-youtube/assets/144512077/7037165f-3831-48cf-9066-f083330e4e71)
... it doesn't really work for me . I'm on brave - also adding  'enable' or 'disable' to the toggles would be helpful...
other than that, this is great! thank you.

**Comment by proffapt** [comment]
hmm, youtube changed their code ¯\_(ツ)_/¯ .
@simran-cs would you like to handle it?

**Comment by mightysimran** [comment]
Yes, @proffapt! 🛠️
