### ISSUE TITLE
Implement privacy enhancement features

### ISSUE THREAD

**Issue by proffapt** [proffapt/own-youtube#4]
**Some of my To-Do(s).** Will be great if people out there help me out in achieving the goal to make this the _all in one extension ever needed for youtube_.

- [ ] Integrate sponosor-segment blocking.
- [ ] Integrate tracker remover.
- [ ] Integrate adblocker.

**Comment by makukaka** [comment]
Not too familiar with coding/github, but in shadow of recent events of yt blocking adblockers, i could help make translation of this plugin into Latvian and possibly other languages over some time, so more people could find it easy to use.

**Comment by proffapt** [comment]
If you are interested, then go ahead 🙌🏻 
Tell me if you will be working on a part or this whole will assign you the issue accordingly.

**Comment by makukaka** [comment]
Hello,
Im sorry i was bit faded away and forgot to check e-mail (adhd thingy), but yeah I can do it, was using the extension all this time and it works like a charm!

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by proffapt** [comment]
Yes, feel free to implement it.
