### ISSUE TITLE
redundant padding on YouTube's homepage and subscriptions, and misalignment of contents in watch later/ playlists section

### ISSUE THREAD

**Issue by mightysimran** [proffapt/own-youtube#41]
The issue seems to have somehow arisen yet again, wherein if #5 is fixed, #9 surfaces and vice versa.
🛠️ WIP to fix both the issues once and for all — unless YouTube rolls out some major changes in future updates (~_~メ)

https://github.com/proffapt/own-youtube/assets/138142257/02519cc6-1295-4db9-8cf9-4c0909d80c01

<img src="https://github.com/proffapt/own-youtube/assets/138142257/77bf761c-abec-4275-8f67-d4734d0082dd" width="49%" height="auto"/>
<img src="https://github.com/proffapt/own-youtube/assets/138142257/02b4997b-3c7f-4f6a-a480-40a16a4da928" width="49%" height="auto"/>

**Comment by proffapt** [comment]
Interesting..
