### ISSUE TITLE
Inconsistent resize/positioned of the video when sidebar removed from sidebar option

### ISSUE THREAD

**Issue by Starcraft426** [proffapt/own-youtube#42]
**Bug description**
When centered, the video is not always consistently resized or positioned like shown after.
Deactivating the extension fixes the problem so it must be linked to it.

**Screenshots**
<img width="1792" alt="Screenshot 2023-10-19 at 15 25 10" src="https://github.com/proffapt/own-youtube/assets/57520713/8eec0695-bfe6-4fcb-905e-6841e8cb0c04">

**System infos**
 - OS: MacOs Ventura 13.5.1
 - Browser: Chrome 118.0.5993.70
 - Lastest version of the extension downloaded on the 19/10

**Comment by mightysimran** [comment]
I have been using the extension for a while, `Center Contents` works perfectly for me. 

https://github.com/proffapt/own-youtube/assets/138142257/b5cdbd26-5ab5-4747-94e4-e1635af15643

**System information:**

- Operating System: Windows 11 NT
- Browser: Chrome Version 118.0.5993.71

**Comment by proffapt** [comment]
try theatre mode maybe?
Weird cause I can't replicate the bug..

<img width="1680" alt="image" src="https://github.com/proffapt/own-youtube/assets/86282911/587c1c4f-3beb-4965-94ca-58819fee520e">
<img width="1680" alt="image" src="https://github.com/proffapt/own-youtube/assets/86282911/243fb4f2-297f-40e5-9505-a8ab95782f6e">

**Comment by mightysimran** [comment]
> I can't replicate the bug

Neither can I. 
Works just fine irrespective of mode.

**Default View**
![image](https://github.com/proffapt/own-youtube/assets/138142257/081969bd-a978-4f7e-b738-31ddf29d62ec)

**Theater Mode**
![image](https://github.com/proffapt/own-youtube/assets/138142257/98384a4e-8f91-439a-b21e-e0768a3a4e0a)

**Comment by Starcraft426** [comment]
I don't know, I just downloaded the extension, used it and it happened. Looks like I am on default view. I also noticed that these dont show and the video bar is 
<img width="1218" alt="Screenshot 2023-10-21 at 11 30 46" src="https://github.com/proffapt/own-youtube/assets/57520713/5b623ff6-2583-4411-aae1-64c416ed859a">

**Comment by Starcraft426** [comment]
Missliked

**Comment by Starcraft426** [comment]
Sorry for the closed and reopened, I misscliked while trying to comment.
As I saw, I am on normal mode. It looks like the page is loaded and then the video frame resized and centered without the video itself being resized:
**size of the container**
<img width="294" alt="Screenshot 2023-10-21 at 11 35 04" src="https://github.com/proffapt/own-youtube/assets/57520713/6b5383ec-b566-4aa9-ba02-a2f103959376">
**size of the video**
<img width="297" alt="Screenshot 2023-10-21 at 11 34 38" src="https://github.com/proffapt/own-youtube/assets/57520713/7decb2fe-e849-4584-8dfe-d416c83a1916">

I also noticed the looking at you screen captures that lots of the buttons of the bottom of the video don't show when the extension is activated (also the mini video viewer is partly hidden):
**when activated**
<img width="883" alt="Screenshot 2023-10-21 at 11 30 33" src="https://github.com/proffapt/own-youtube/assets/57520713/8245bf50-986e-40a9-9543-73a031fe0c80">
**when deactivated**
<img width="1218" alt="Screenshot 2023-10-21 at 11 30 46" src="https://github.com/proffapt/own-youtube/assets/57520713/49df7959-2fea-4916-8e03-6801da3ecfe4">

It looks like the video bar isn't resized too:
<img width="1261" alt="Screenshot 2023-10-21 at 11 41 30" src="https://github.com/proffapt/own-youtube/assets/57520713/527ad2bb-6740-434a-b39f-ab557d974638">

I also have some errors on the extension:
<img width="695" alt="Screenshot 2023-10-21 at 11 43 00" src="https://github.com/proffapt/own-youtube/assets/57520713/c73a54f7-992b-4e90-989c-512b6a761fb0">

Finally, the content is centered by default, while not being checked in the menu:
<img width="1774" alt="Screenshot 2023-10-21 at 11 45 11" src="https://github.com/proffapt/own-youtube/assets/57520713/e2f96ce1-b8a0-4dd8-b923-60704818fb83">
It is probably that causing all the problems.

**Comment by Starcraft426** [comment]
Also, just notice it doesn't apply to all videos. That's weird.

**Comment by Starcraft426** [comment]
Just noticed a patch was created 3 days ago. I will check it tomorrow and close the bug if solved

**Comment by mightysimran** [comment]
It must be device specific, imo. I use this extension almost all the time, didn't encounter this issue on any of the videos so far.

**Comment by Starcraft426** [comment]
May be just due to something handled bu macos but not modified on widows. Are you both on windows?  I’ll try and see if I can reproduce it tomorrow on a windows machine but i don’t think I’ll be able to if you can’t. Also i keep searching what is causing it

**Comment by proffapt** [comment]
I am on macos

**Comment by Starcraft426** [comment]
Somehow, by downloading the "new" version, the bug fixed itself. I don't know how, I tried to check if there was any difference between files but nothing... I have not a single clue of how it happened how how it fixed and how the old one is still bugged but now that is works properly i'm happy with it.

**Comment by Starcraft426** [comment]
Back for some reason, i'll try to figure out why

**Comment by Starcraft426** [comment]
nvw it is working fine

**Comment by Starcraft426** [comment]
finally found out where it was coming from but I don't know why. I might look into it later. I'll reopen if i do so

**Comment by Starcraft426** [comment]
Center content works fine but sidebar doesn't

**Comment by mightysimran** [comment]
> Center content works fine but sidebar doesn't

It'd be convenient if you demonstrate the exact issue through screenshot(s) or screencast.

**Comment by Starcraft426** [comment]
I'll give some later on but first i think i found where the issue is

```
/* Center contents when the sidebar is entirely hidden */
html[global_enable="true"][remove_entire_sidebar="true"] ytd-watch-flexy[flexy][is-two-columns_]:not([fullscreen]):not([theater]) {
	--ytd-watch-flexy-max-player-width: calc(var(--ytd-watch-flexy-chat-max-height)*var(--ytd-watch-flexy-width-ratio)/var(--ytd-watch-flexy-height-ratio)) !important
}
```
This is used when the entire sidebar (center content is checked) is removed to resize the video. But it isn't done when the sidebar (sidebar is checked) is removed, so the size is wrong. 
I was also wondering what is the difference between these two in the first place

**Comment by Starcraft426** [comment]
Here are the screenshots.

Without sidebar nor center content:
<img width="1787" alt="Screenshot 2024-01-09 at 12 22 12" src="https://github.com/proffapt/own-youtube/assets/57520713/0934b390-40c8-4564-8354-e5ac7c32fcf6">

With sidebar:
<img width="1789" alt="Screenshot 2024-01-09 at 12 22 35" src="https://github.com/proffapt/own-youtube/assets/57520713/e8f71d48-d6c0-4699-ac3b-45666c716e69">

With center content:
<img width="1788" alt="Screenshot 2024-01-09 at 12 22 54" src="https://github.com/proffapt/own-youtube/assets/57520713/6e2b573d-a3b9-47c1-9458-ad8938f65bd8">
