### ISSUE TITLE
Function to automatically unpause video when popup "continue watching appears"

### ISSUE THREAD

**Issue by Starcraft426** [proffapt/own-youtube#46]
**Is your feature request related to a problem? Please describe.**
This popup is just annoying when you are listening to music, it could probably be clicked as the skipped button is done.

**Describe the solution you'd like**
Make the script click the button 
```html
<button class="yt-spec-button-shape-next yt-spec-button-shape-next--text yt-spec-button-shape-next--call-to-action yt-spec-button-shape-next--size-m" aria-label="Oui" title="" style="">
```
and probably add the related name/funtions on the html / css / js option for it

**Describe alternatives you've considered**
At least doing it by default is good too

**Comment by Starcraft426** [comment]
I'll make a PR soon, after I get the script to click it when the window is shown.

**Comment by proffapt** [comment]
great!!

**Comment by Starcraft426** [comment]
Pull request created

**Comment by Starcraft426** [comment]
merged
