### ISSUE TITLE
Remove unnecessary padding in subscription page

### ISSUE THREAD

**Issue by proffapt** [proffapt/own-youtube#5]
<img width="354" alt="image" src="https://user-images.githubusercontent.com/86282911/194901495-96d14d4b-90e0-49da-ac87-fd56c9e67736.png">

Wasn't able to remove it, later on; open for ideas ;)

**Comment by nalin-programmer** [comment]
assign me this task

**Comment by proffapt** [comment]
> can you please elaborate the issue

can you see that pain below the ham-burger menu, it had icons and links which this extension was used to remove; what I wanted to do is, remove that place too where those icons were placed, so that videos have more space for their thumbnails and they are centred.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/86282911/194910393-396d14bc-9bde-43d9-8481-ca24587f2333.png">
see the video-grid isn't centred

**Comment by proffapt** [comment]
@nalin-programmer any updates or shall I assign it?

**Comment by Omksaini2003** [comment]
assign me this issue please

**Comment by proffapt** [comment]
> assign me this issue please
> 

All the best!

**Comment by Omksaini2003** [comment]
this project is very interesting and useful to me. i am still a beginner in this field therefore it would be very helpful to me if you could redirect me to some resources and/or explain me how this extension filter content thorough scripts. i spent last night but couldn't grasp much. hence asking for help.

**Comment by proffapt** [comment]
You could try learning about how you can inject a js and a css file into the webpage using an extension; that's what it used internally.
It modifies the css and removes those html elements.

**Comment by Alph3ga** [comment]
is this issue fixed? because i cannot figure out how to recreate it

**Comment by proffapt** [comment]
Solved in https://github.com/proffapt/own-youtube/pull/16
